name: Manual Greeting

on:
  workflow_dispatch:
    inputs:
      student_name:
        description: "Имя ученика для приветствия"
        required: true
        default: "Школьник"

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: greeting
        run: |
          echo "hi, ${{ github.event.inputs.student_name }}!"
          echo "run number ${{ github.run_number }}"

      # TODO:
      # 1. Добавь шаг, который выводит приветствие для inputs.student_name
      # 2. Попробуй дополнительно вывести номер запуска: GITHUB_RUN_NUMBER
